//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.20 at 08:30:51 PM CET 
//


package odm_v1_3;


import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cdisc.ns.odm.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cdisc.ns.odm.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ODM }
     * 
     */
    public ODM createODM() {
        return new ODM();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData }
     * 
     */
    public ODM.ClinicalData createODMClinicalData() {
        return new ODM.ClinicalData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData }
     * 
     */
    public ODM.ClinicalData.SubjectData createODMClinicalDataSubjectData() {
        return new ODM.ClinicalData.SubjectData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData createODMClinicalDataSubjectDataStudyEventData() {
        return new ODM.ClinicalData.SubjectData.StudyEventData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData createODMClinicalDataSubjectDataStudyEventDataFormData() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData createODMClinicalDataSubjectDataStudyEventDataFormDataItemGroupData() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation createODMClinicalDataSubjectDataStudyEventDataFormDataAnnotation() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag createODMClinicalDataSubjectDataStudyEventDataFormDataAnnotationFlag() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord createODMClinicalDataSubjectDataStudyEventDataFormDataAuditRecord() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.AuditRecord }
     * 
     */
    public ODM.ClinicalData.SubjectData.AuditRecord createODMClinicalDataSubjectDataAuditRecord() {
        return new ODM.ClinicalData.SubjectData.AuditRecord();
    }

    /**
     * Create an instance of {@link ODM.AdminData }
     * 
     */
    public ODM.AdminData createODMAdminData() {
        return new ODM.AdminData();
    }

    /**
     * Create an instance of {@link ODM.Study }
     * 
     */
    public ODM.Study createODMStudy() {
        return new ODM.Study();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion }
     * 
     */
    public ODM.Study.MetaDataVersion createODMStudyMetaDataVersion() {
        return new ODM.Study.MetaDataVersion();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.MethodDef }
     * 
     */
    public ODM.Study.MetaDataVersion.MethodDef createODMStudyMetaDataVersionMethodDef() {
        return new ODM.Study.MetaDataVersion.MethodDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.MethodDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.MethodDef.Description createODMStudyMetaDataVersionMethodDefDescription() {
        return new ODM.Study.MetaDataVersion.MethodDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ConditionDef }
     * 
     */
    public ODM.Study.MetaDataVersion.ConditionDef createODMStudyMetaDataVersionConditionDef() {
        return new ODM.Study.MetaDataVersion.ConditionDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ConditionDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.ConditionDef.Description createODMStudyMetaDataVersionConditionDefDescription() {
        return new ODM.Study.MetaDataVersion.ConditionDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.CodeList }
     * 
     */
    public ODM.Study.MetaDataVersion.CodeList createODMStudyMetaDataVersionCodeList() {
        return new ODM.Study.MetaDataVersion.CodeList();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.CodeList.CodeListItem }
     * 
     */
    public ODM.Study.MetaDataVersion.CodeList.CodeListItem createODMStudyMetaDataVersionCodeListCodeListItem() {
        return new ODM.Study.MetaDataVersion.CodeList.CodeListItem();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode }
     * 
     */
    public ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode createODMStudyMetaDataVersionCodeListCodeListItemDecode() {
        return new ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef createODMStudyMetaDataVersionItemDef() {
        return new ODM.Study.MetaDataVersion.ItemDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.Question }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.Question createODMStudyMetaDataVersionItemDefQuestion() {
        return new ODM.Study.MetaDataVersion.ItemDef.Question();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.Description createODMStudyMetaDataVersionItemDefDescription() {
        return new ODM.Study.MetaDataVersion.ItemDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemGroupDef }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemGroupDef createODMStudyMetaDataVersionItemGroupDef() {
        return new ODM.Study.MetaDataVersion.ItemGroupDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemGroupDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemGroupDef.Description createODMStudyMetaDataVersionItemGroupDefDescription() {
        return new ODM.Study.MetaDataVersion.ItemGroupDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.FormDef }
     * 
     */
    public ODM.Study.MetaDataVersion.FormDef createODMStudyMetaDataVersionFormDef() {
        return new ODM.Study.MetaDataVersion.FormDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.FormDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.FormDef.Description createODMStudyMetaDataVersionFormDefDescription() {
        return new ODM.Study.MetaDataVersion.FormDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.StudyEventDef }
     * 
     */
    public ODM.Study.MetaDataVersion.StudyEventDef createODMStudyMetaDataVersionStudyEventDef() {
        return new ODM.Study.MetaDataVersion.StudyEventDef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.StudyEventDef.Description }
     * 
     */
    public ODM.Study.MetaDataVersion.StudyEventDef.Description createODMStudyMetaDataVersionStudyEventDefDescription() {
        return new ODM.Study.MetaDataVersion.StudyEventDef.Description();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.Protocol }
     * 
     */
    public ODM.Study.MetaDataVersion.Protocol createODMStudyMetaDataVersionProtocol() {
        return new ODM.Study.MetaDataVersion.Protocol();
    }

    /**
     * Create an instance of {@link ODM.Study.BasicDefinitions }
     * 
     */
    public ODM.Study.BasicDefinitions createODMStudyBasicDefinitions() {
        return new ODM.Study.BasicDefinitions();
    }

    /**
     * Create an instance of {@link ODM.Study.BasicDefinitions.MeasurementUnit }
     * 
     */
    public ODM.Study.BasicDefinitions.MeasurementUnit createODMStudyBasicDefinitionsMeasurementUnit() {
        return new ODM.Study.BasicDefinitions.MeasurementUnit();
    }

    /**
     * Create an instance of {@link ODM.Study.BasicDefinitions.MeasurementUnit.Symbol }
     * 
     */
    public ODM.Study.BasicDefinitions.MeasurementUnit.Symbol createODMStudyBasicDefinitionsMeasurementUnitSymbol() {
        return new ODM.Study.BasicDefinitions.MeasurementUnit.Symbol();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData.ItemData }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData.ItemData createODMClinicalDataSubjectDataStudyEventDataFormDataItemGroupDataItemData() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.ItemGroupData.ItemData();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag.FlagValue }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag.FlagValue createODMClinicalDataSubjectDataStudyEventDataFormDataAnnotationFlagFlagValue() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.Annotation.Flag.FlagValue();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.UserRef }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.UserRef createODMClinicalDataSubjectDataStudyEventDataFormDataAuditRecordUserRef() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.UserRef();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.LocationRef }
     * 
     */
    public ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.LocationRef createODMClinicalDataSubjectDataStudyEventDataFormDataAuditRecordLocationRef() {
        return new ODM.ClinicalData.SubjectData.StudyEventData.FormData.AuditRecord.LocationRef();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.AuditRecord.UserRef }
     * 
     */
    public ODM.ClinicalData.SubjectData.AuditRecord.UserRef createODMClinicalDataSubjectDataAuditRecordUserRef() {
        return new ODM.ClinicalData.SubjectData.AuditRecord.UserRef();
    }

    /**
     * Create an instance of {@link ODM.ClinicalData.SubjectData.AuditRecord.LocationRef }
     * 
     */
    public ODM.ClinicalData.SubjectData.AuditRecord.LocationRef createODMClinicalDataSubjectDataAuditRecordLocationRef() {
        return new ODM.ClinicalData.SubjectData.AuditRecord.LocationRef();
    }

    /**
     * Create an instance of {@link ODM.AdminData.User }
     * 
     */
    public ODM.AdminData.User createODMAdminDataUser() {
        return new ODM.AdminData.User();
    }

    /**
     * Create an instance of {@link ODM.Study.GlobalVariables }
     * 
     */
    public ODM.Study.GlobalVariables createODMStudyGlobalVariables() {
        return new ODM.Study.GlobalVariables();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.MethodDef.FormalExpression }
     * 
     */
    public ODM.Study.MetaDataVersion.MethodDef.FormalExpression createODMStudyMetaDataVersionMethodDefFormalExpression() {
        return new ODM.Study.MetaDataVersion.MethodDef.FormalExpression();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.MethodDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.MethodDef.Description.TranslatedText createODMStudyMetaDataVersionMethodDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.MethodDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ConditionDef.FormalExpression }
     * 
     */
    public ODM.Study.MetaDataVersion.ConditionDef.FormalExpression createODMStudyMetaDataVersionConditionDefFormalExpression() {
        return new ODM.Study.MetaDataVersion.ConditionDef.FormalExpression();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ConditionDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.ConditionDef.Description.TranslatedText createODMStudyMetaDataVersionConditionDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.ConditionDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode.TranslatedText createODMStudyMetaDataVersionCodeListCodeListItemDecodeTranslatedText() {
        return new ODM.Study.MetaDataVersion.CodeList.CodeListItem.Decode.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.CodeListRef }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.CodeListRef createODMStudyMetaDataVersionItemDefCodeListRef() {
        return new ODM.Study.MetaDataVersion.ItemDef.CodeListRef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.MeasurementUnitRef }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.MeasurementUnitRef createODMStudyMetaDataVersionItemDefMeasurementUnitRef() {
        return new ODM.Study.MetaDataVersion.ItemDef.MeasurementUnitRef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.RangeCheck }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.RangeCheck createODMStudyMetaDataVersionItemDefRangeCheck() {
        return new ODM.Study.MetaDataVersion.ItemDef.RangeCheck();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.Question.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.Question.TranslatedText createODMStudyMetaDataVersionItemDefQuestionTranslatedText() {
        return new ODM.Study.MetaDataVersion.ItemDef.Question.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemDef.Description.TranslatedText createODMStudyMetaDataVersionItemDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.ItemDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemGroupDef.ItemRef }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemGroupDef.ItemRef createODMStudyMetaDataVersionItemGroupDefItemRef() {
        return new ODM.Study.MetaDataVersion.ItemGroupDef.ItemRef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.ItemGroupDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.ItemGroupDef.Description.TranslatedText createODMStudyMetaDataVersionItemGroupDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.ItemGroupDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.FormDef.ItemGroupRef }
     * 
     */
    public ODM.Study.MetaDataVersion.FormDef.ItemGroupRef createODMStudyMetaDataVersionFormDefItemGroupRef() {
        return new ODM.Study.MetaDataVersion.FormDef.ItemGroupRef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.FormDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.FormDef.Description.TranslatedText createODMStudyMetaDataVersionFormDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.FormDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.StudyEventDef.FormRef }
     * 
     */
    public ODM.Study.MetaDataVersion.StudyEventDef.FormRef createODMStudyMetaDataVersionStudyEventDefFormRef() {
        return new ODM.Study.MetaDataVersion.StudyEventDef.FormRef();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.StudyEventDef.Description.TranslatedText }
     * 
     */
    public ODM.Study.MetaDataVersion.StudyEventDef.Description.TranslatedText createODMStudyMetaDataVersionStudyEventDefDescriptionTranslatedText() {
        return new ODM.Study.MetaDataVersion.StudyEventDef.Description.TranslatedText();
    }

    /**
     * Create an instance of {@link ODM.Study.MetaDataVersion.Protocol.StudyEventRef }
     * 
     */
    public ODM.Study.MetaDataVersion.Protocol.StudyEventRef createODMStudyMetaDataVersionProtocolStudyEventRef() {
        return new ODM.Study.MetaDataVersion.Protocol.StudyEventRef();
    }

    /**
     * Create an instance of {@link ODM.Study.BasicDefinitions.MeasurementUnit.Symbol.TranslatedText }
     * 
     */
    public ODM.Study.BasicDefinitions.MeasurementUnit.Symbol.TranslatedText createODMStudyBasicDefinitionsMeasurementUnitSymbolTranslatedText() {
        return new ODM.Study.BasicDefinitions.MeasurementUnit.Symbol.TranslatedText();
    }

}
