//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.20 at 08:30:51 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.cdisc.org/ns/odm/v1.3", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package odm_v1_3;
